### ISSUE TITLE
MSYS2 temporarily broken

### ISSUE THREAD

**Issue by ed-alertedh** [open-tool-forge/fpga-toolchain#30]
see https://github.com/msys2/MSYS2-packages/pull/2022
temporary fix here (hoepfully) https://github.com/mesonbuild/meson/commit/d438a2d842058e00fc2326fbfc4a9e220afa8396

**Comment by edbordin** [comment]
MSYS2 has fixed it.

**Comment by edbordin** [comment]
Now we're hitting this https://github.com/msys2/MSYS2-packages/issues/2033
